name: macOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Install Xcode Command Line Tools
        run: xcode-select --install || true

      - name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Cache xmake packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.xmake/packages
            ~/.xmake/cache
          key: ${{ runner.os }}-${{ runner.arch }}-xmake-${{ hashFiles('xmake.lua', 'xmake/*.lua') }}
          restore-keys: |
              ${{ runner.os }}-${{ runner.arch }}-xmake-

      - name: Cache FastNoise2 build
        id: cache-fastnoise2
        uses: actions/cache@v5
        with:
          path: thirdparty/FastNoise2/build
          key: fastnoise2-${{ runner.os }}-${{ matrix.arch }}-${{ hashFiles('thirdparty/FastNoise2/**') }}
          restore-keys: |
            fastnoise2-${{ runner.os }}-${{ matrix.arch }}-

      - name: Install dependencies
        shell: bash
        run: xmake require -y
      
      - name: Build FastNoise2 (if not cached)
        if: steps.cache-fastnoise2.outputs.cache-hit != 'true'
        shell : bash
        run: xmake build FastNoise2

      - name: Configure & Build
        run: |
          xmake f -p macosx --toolchain=clang -a ${{ matrix.arch }} -y -v
          xmake build fractal