name: macOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Configure & Build
        run: |
          xmake f -p macosx --toolchain=clang -a ${{ matrix.arch }} -y -v
          xmake

      - name: Package executable
        run: |
          target=$(grep 'target' xmake.lua | cut -d'"' -f2)
          mkdir -p artifacts
          cp "build/macosx/${{ matrix.arch }}/release/${target}" artifacts/
